---
title: "Inferencia causal"
subtitle: "Correlación no es causalidad"
---

# ¿Qué es la inferencia causal?
## Definiciones

La causalidad la definimos a partir del contrafactual. Usamos el modelo de resultados potenciales

- $Y_i(0)$ es el resultado potencial del individuo $i$ cuando **no** recibe el tratamiento
- $Y_i(1)$ es el resultado potencial del individuo $i$ cuando **si** recibe el tratamiento
- Para cada individuo, solo observamos el estatus de tratamiento $D_i\in\{0,1\}$, y el resultado realizado, $Y_i$

$$
Y_i := Y_i(D_i) =
\begin{cases}
Y_i(0) & \text{if } D_i = 0, \\
Y_i(1) & \text{if } D_i = 1.
\end{cases}
$$

## Definiciones

- El tratamiento para un individuo $i$ es
$$
\Delta_i=Y_i(1)-Y_i(0)
$$

Esto no se puede obtener directamente. Solo observamos uno de los dos resultados. Es el problema fundamental de la inferencia causal. Nos enfocamos en hacer inferencias sobre la diferencia a nivel poblacional. Definimos los siguientes parámetros

:::: {.columns}
::: {.column width="33%"}
::: {.tarjeta .acento}
[ATE]{.tarjeta-titulo}

$$
E[Y_i(1)-Y_i(0)]
$$
:::
:::

::: {.column width="33%"}
::: {.tarjeta}
[ATT]{.tarjeta-titulo}
$$
E[Y_i(1)-Y_i(0)|D_i=1]
$$
:::
:::

::: {.column width="34%"}
::: {.tarjeta}
[ATU]{.tarjeta-titulo}
$$
E[Y_i(1)-Y_i(0)|D_i=0]
$$
:::
:::
::::

Si definimos $\pi$ como la proporción de individuos en tratamiento, entonces

$$
ATE=\pi \times ATT+(1-\pi)\times ATU
$$

## Definiciones
Definimos la diferencia en resultados promedios como

$$
SDO=E(Y_i(1)|D_i=1)-E(Y_i(0)|D_i=0)
$$
Como $Y=Y(1)$ si $D=1$, y usando la descomposición anterior del ATE, se puede mostrar, siguiendo a [@cunningham2026causal](https://mixtape.scunning.com/04-potential_outcomes_and_randomization#fnref10), que
$$
\begin{aligned}
\underbrace{E[Y \mid D=1] - E[Y \mid D=0]}_{\text{SDO}}
  &= \underbrace{E[Y(1)] - E[Y(0)]}_{\text{ATE}} \\
  &\quad + \underbrace{E[Y(0) \mid D=1] - E[Y(0) \mid D=0]}_{\text{Sesgo de selección}} \\
  &\quad + \underbrace{(1-\pi)(ATT - ATU)}_{\text{Heterogeneous treatment effect bias}}
\end{aligned}
$$

## Correlación y causalidad

SDO se puede estimar con los datos

$$
SDO = \frac{1}{N_T} \sum_{i=1}^{n} \left( y_i \mid d_i = 1 \right) - \frac{1}{N_C} \sum_{i=1}^{n} \left( y_i \mid d_i = 0 \right)
$$
Luego, esta cantidad corresponde al efecto causal, ATE, si los términos de sesgo son cero. Si no lo son, SDO nos entrega correlación y no causalidad

<br>

::: {.callout-note title="Pregunta"}
¿Cómo podemos eliminar el sesgo de seleccióny el sesgo de tratamiento heterogeneo?
:::


# RCT y asignación aleatoria

## Aleatorización e independencia

Decimos que el tratamiento es independiente de los resultados potenciales si la asignación a tratamiento no tiene nada que ver con los resultados potenciales. La aleatorización es un mecanismo, el mejor.

$$
(Y_i(1),Y_i(0))\perp  D_i
$$
Por lo tanto 
$$
E[Y(0)|D=1]=E[Y(0)] \quad \text{y}\quad  E[Y(0)|D=0]=E[Y(0)]
$$
luego 
$$
E[Y(0) \mid D=1] - E[Y(0) \mid D=0]=E[Y(0)]-E[Y(0)]=0
$$
De manera similar se puede mostrar que bajo asignación aleatoria $ATT=ATU$, luego $SDO=ATE$

## Estimación usando regresión

Sea $W$ un vector de covariables pre-determinadas (son previas a la asignación), y la asignación a tratamiento es independiente de ellas y los resultados potenciales, bajo el supuesto de linealidad

$$
Y=\alpha D+\beta'X+\epsilon; \quad E[\epsilon\mid D,X]=0
$$
Por tanto

$$
E[Y|D,W]=\alpha D+\beta'X
$$
donde $X=(1,W)$. En esta formulación $\alpha=ATE$

## Referencias

::: {#refs}
:::